import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { spawn } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const srcDir = path.join(root, "src");
const target = process.argv.find((argument) => argument.startsWith("--target="))?.split("=")[1] || "chrome";
const env = process.argv.find((argument) => argument.startsWith("--env="))?.split("=")[1] || "production";
// PR builds (.github/workflows/pr.yml) use these to keep validation builds
// clearly distinct from a real release's version — see AGENTS.md
// (Versioning). --version-override replaces manifest.version outright
// (must stay Chrome/Firefox-manifest-valid: up to four dot-separated
// integers, no letters/hyphens); --version-name sets Chrome's separate
// human-readable version_name field, which has no such format restriction.
const versionOverride = process.argv.find((argument) => argument.startsWith("--version-override="))?.split("=")[1];
const versionName = process.argv.find((argument) => argument.startsWith("--version-name="))?.split("=")[1];
const distDir = path.join(root, target === "chrome" ? "dist" : `dist-${target}`);

if (!new Set(["chrome", "firefox", "safari"]).has(target)) {
  throw new Error(`Unsupported build target: ${target}`);
}
if (!new Set(["production", "local"]).has(env)) {
  throw new Error(`Unsupported build env: ${env}. Use --env=local to point at the local Compose stack (see docs/testing-locally.md).`);
}

const pkg = JSON.parse(await readFile(path.join(root, "package.json"), "utf8"));

await new Promise((resolve, reject) => {
  const child = spawn(process.execPath, [path.join(root, "scripts", "generate-icons.mjs")], {
    cwd: root,
    stdio: "inherit"
  });

  child.on("exit", (code) => {
    if (code === 0) {
      resolve();
      return;
    }

    reject(new Error(`Icon generation failed with code ${code}`));
  });
  child.on("error", reject);
});

await rm(distDir, { recursive: true, force: true });
await mkdir(distDir, { recursive: true });
await cp(srcDir, distDir, { recursive: true });

// --env=local points the extension at the standardized local Compose stack
// (docs/testing-locally.md) instead of production. This overwrites the
// *build output's* lib/config.js only — src/lib/config.js (the production
// default) is never touched.
if (env === "local") {
  const localConfig = `// Generated by scripts/build.mjs --env=local. Do not edit; edit src/lib/config.js instead.
export const API_BASE_URL = "http://localhost:8792";
export const AUTH_ISSUER = "http://localhost:8793/realms/novel-tracker";
// One hint-less provider: the local/e2e realms federate neither Google nor
// Apple, so Keycloak has to show its own login form for the seeded test user.
export const AUTH_PROVIDERS = Object.freeze([
  Object.freeze({ id: "keycloak", label: "Sign in", idpHint: "", icon: "user" })
]);
`;
  await writeFile(path.join(distDir, "lib", "config.js"), localConfig, "utf8");
}

const manifestPath = path.join(distDir, "manifest.json");
const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
manifest.version = versionOverride || pkg.version;
if (versionName && target === "chrome") {
  manifest.version_name = versionName;
}
if (env === "local") {
  manifest.host_permissions = [
    ...(manifest.host_permissions || []),
    "http://localhost:8792/*",
    "http://localhost:8793/*"
  ];
}
if (target === "firefox") {
  manifest.background = { scripts: ["background.js"], type: "module" };
  manifest.browser_specific_settings = {
    gecko: {
      id: "novel-tracker@bghimire.com",
      strict_min_version: "140.0",
      data_collection_permissions: {
        required: ["none"],
        optional: [
          "authenticationInfo",
          "personallyIdentifyingInfo",
          "browsingActivity",
          "websiteActivity",
          "websiteContent"
        ]
      }
    },
    gecko_android: { strict_min_version: "142.0" }
  };
}
if (target === "safari") {
  manifest.permissions = manifest.permissions.filter((permission) => permission !== "identity");
  if (!manifest.permissions.includes("nativeMessaging")) manifest.permissions.push("nativeMessaging");
  manifest.background = { service_worker: "background.js" };
  manifest.browser_specific_settings = {
    safari: { strict_min_version: "17.0" }
  };
  // Bundle from distDir (not srcDir) so a --env=local build's overwritten
  // lib/config.js above is what actually gets inlined into the bundle.
  // Loaded lazily so chrome/firefox builds never need esbuild resolvable.
  const { build: bundle } = await import("esbuild");
  await bundle({
    entryPoints: [path.join(distDir, "background.js")],
    outfile: path.join(distDir, "background.js"),
    bundle: true,
    format: "iife",
    platform: "browser",
    target: "safari17",
    legalComments: "none",
    allowOverwrite: true
  });
}
await writeFile(manifestPath, JSON.stringify(manifest, null, 2) + "\n", "utf8");

console.log(`Built ${target} extension (${env}) to ${distDir}`);
